⬇️ temp downgrade TS due to react-docgen-typescript
getting error TypeError: (tag.text || "").trim is not a function
when building storybook with react-docgen-typescript
in newer TS versions